<a href="https://colab.research.google.com/github/pathansayama/LetsUpgrade-DataScience-SayamaPathan-Batch1/blob/main/Assignment3.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

**Assignment 3**

1.Create a numpy array starting from 2 till 50 with a stepsize of 3.

In [ ]:
import numpy as np
# Start = 2, Stop = 50, Step Size = 3

array_np = np.arange(2, 50, 3)
print(array_np)

[ 2  5  8 11 14 17 20 23 26 29 32 35 38 41 44 47]


2.

In [ ]:
import numpy

lst1= input("List1=")
lst2= input("List2=")

a = numpy.asarray(lst1)
b = numpy.asarray(lst2)

print("Array1: ", a)
print("Array2: ", b)

numpy.concatenate((a,b),axis=0)


List1=12,4,8
List2=3,5
Array1:  12,4,8
Array2:  3,5


ValueError: ignored

3.

In [ ]:

import numpy as np
 
a1 = np.array( [[ 1, 2, 3],
              [ 4, 2, 5]] )
print("No. of dimensions: ", a1.ndim)
 
print("Size of array: ", a1.size)

No. of dimensions:  2
Size of array:  6


4.

In [25]:
import numpy as np
a = np.arange(6)
a2 = a[np.newaxis, :]
a2.shape

(1, 6)

5.

In [26]:
import numpy as np 
  
a = np.array([[10, 20], 
              [30, 40]]) 
  
b = np.array([[50, 60], 
              [70, 80]]) 
print("Vertical Stacking:\n", np.vstack((a, b))) 
print("\nHorizontal Stacking:\n", np.hstack((a, b))) 

Vertical Stacking:
 [[10 20]
 [30 40]
 [50 60]
 [70 80]]

Horizontal Stacking:
 [[10 20 50 60]
 [30 40 70 80]]


6.

In [27]:
a_list = [1, 1, 2, 2, 3]
print(a_list)

a_set = set(a_list)
print(a_set)

number_of_unique_items = len(a_set)
print(number_of_unique_items)

[1, 1, 2, 2, 3]
{1, 2, 3}
3
